# Site Settings
title: egg
email: r90323011@ntu.edu.tw
description: egg's description
baseurl: ""
url: "https://doltegg.github.io/blackcards"
google_analytics: "UA-99616615-1"

# User Settings
username: Thiago Rossener
user_description: Desenvolvedor front-end remoto & mochileiro nas horas vagas.
github_username: thiagorossener
facebook_username: thiagorossener
twitter_username: thiagorossener
instagram_username: thiagorossener
linkedin_username: thiagorossener
medium_username: thiagorossener
disqus_username: rossener

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 8
paginate_path: "/blackcards/page:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jekyll-redirect-from
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Portfólio
    url: /portfolio/
  - title: Sobre mim
    url: /sobre-mim/
  - title: Contato
    url: /contato/
    

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
